### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by michaeladler** [bhmj/expression_parser#3]
Hi Michael,

thank your for creating jsonslice, it's a very nice project. I noticed that this project is a dependency of jsonslice and it is missing a license.  While jsonslice is MIT-licensed, it is unclear what the license of this project is. I guess it's meant to be MIT as well, but without an official LICENSE file, I guess from a legal perspective, it's not. So I was wondering if you could you please clarify the license of this project and possibly add a LICENSE file?

**Comment by bhmj** [comment]
Hi Michael!

Thank you very much for your appreciation. This project indeed is released under MIT license as [stated](https://github.com/bhmj/xpression#licence) in a README file, but you're right that it's not that obvious and a proper LICENSE file should be included in a project, so I added one.
